<a href="https://colab.research.google.com/github/jnrahul92/FastAI_Learn/blob/main/C8_Collaborative_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from fastai.collab import *
from fastai.tabular.all import *

In [3]:
path = untar_data(URLs.ML_100k)

```html
<div>
<progress max="4924029" value="4931584"></progress> 100.15% [4931584/4924029 00:00&lt;00:00]</div>

```

In [4]:
ratings = pd.read_csv(path/'u.data', delimiter='\t', header=None, names=['user', 'movie', 'rating', 'timestamp'])
ratings.head()

   user  movie  rating  timestamp
0   196    242       3  881250949
1   186    302       3  891717742
2    22    377       1  878887116
3   244     51       2  880606923
4   166    346       1  886397596

In [5]:
rise_skywalker = np.array([0.98, 0.9, -0.9])

In [6]:
user1 = np.array([0.9, 0.8, -0.6])

In [7]:
(user1*rise_skywalker).sum()

np.float64(2.1420000000000003)

In [8]:
casablanca = np.array([-0.99, -0.3, 0.8])

In [9]:
(user1*casablanca).sum()

np.float64(-1.611)

In [10]:
movies = pd.read_csv(path/'u.item',  delimiter='|', encoding='latin-1', usecols=range(5), names=['movie', 'title', 'release', 'video release', 'imdb url'])
movies.head()

,movie,title,release,video release,imdb url
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(1995)
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%20(1995)
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%20(1995)
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995)

In [11]:
ratings = ratings.merge(movies)
ratings.head()

,user,movie,rating,timestamp,title,release,video release,imdb url
0,196,242,3,881250949,Kolya (1996),24-Jan-1997,NaN,http://us.imdb.com/M/title-exact?Kolya%20(1996)
1,186,302,3,891717742,L.A. Confidential (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?L%2EA%2E+Confidential+(1997)
2,22,377,1,878887116,Heavyweights (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Heavyweights%20(1994)
3,244,51,2,880606923,Legends of the Fall (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Legends%20of%20the%20Fall%20(1994)
4,166,346,1,886397596,Jackie Brown (1997),01-Jan-1997,NaN,http://us.imdb.com/M/title-exact?imdb-title-119396

In [12]:
dls = CollabDataLoaders.from_df(ratings, item_name='title', bs=64)
dls.show_batch()

In [13]:
n_users = len(dls.classes['user'])
n_movies = len(dls.classes['title'])
n_factors = 5

In [14]:
user_factors = torch.randn(n_users, n_factors)
movie_factors = torch.randn(n_movies, n_factors)
user_factors.shape, movie_factors.shape

(torch.Size([944, 5]), torch.Size([1665, 5]))

In [15]:
class DotProduct(Module):
  def __init__(self, n_users, n_movies, n_factors):
    self.user_factors = Embedding(n_users, n_factors)
    self.movie_factors = Embedding(n_movies, n_factors)

  def forward(self, x):
    users = self.user_factors(x[:,0])
    movies = self.movie_factors(x[:,1])
    return (users * movies).sum(dim = 1)

In [16]:
model = DotProduct(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())

In [17]:
learn.fit_one_cycle(5, 5e-3)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>1.325047</td><td>1.338394</td><td>00:07</td></tr><tr><td>1</td><td>1.048074</td><td>1.113242</td><td>00:07</td></tr><tr><td>2</td><td>0.897502</td><td>0.998516</td><td>00:06</td></tr><tr><td>3</td><td>0.785739</td><td>0.910101</td><td>00:07</td></tr><tr><td>4</td><td>0.751446</td><td>0.886033</td><td>00:06</td></tr></tbody></table></div>

In [18]:
class DotProduct(Module):
  def __init__(self, n_users, n_movies, n_factors, y_range = (0.5,5.5)):
    self.user_factors = Embedding(n_users, n_factors)
    self.movie_factors = Embedding(n_movies, n_factors)
    self.y_range = y_range

  def forward(self, x):
    users = self.user_factors(x[:,0])
    movies = self.movie_factors(x[:,1])
    return sigmoid_range((users * movies).sum(dim = 1),*self.y_range)

In [19]:
model = DotProduct(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.958647</td><td>0.993740</td><td>00:07</td></tr><tr><td>1</td><td>0.605816</td><td>0.941620</td><td>00:08</td></tr><tr><td>2</td><td>0.445083</td><td>0.960585</td><td>00:07</td></tr><tr><td>3</td><td>0.332111</td><td>0.969047</td><td>00:07</td></tr><tr><td>4</td><td>0.323691</td><td>0.968924</td><td>00:06</td></tr></tbody></table></div>

In [20]:
class DotProductBias(Module):
  def __init__(self, n_users, n_movies, n_factors, y_range = (0.5,5.5)):
    self.user_factors = Embedding(n_users, n_factors)
    self.user_bias = Embedding(n_users, 1)
    self.movie_factors = Embedding(n_movies, n_factors)
    self.movie_bias = Embedding(n_movies, 1)
    self.y_range = y_range

  def forward(self, x):
    users = self.user_factors(x[:,0])
    movies = self.movie_factors(x[:,1])
    res = (users * movies).sum(dim = 1, keepdim = True)
    res += self.user_bias(x[:,0]) + self.movie_bias(x[:,1])
    return sigmoid_range(res,*self.y_range)

In [21]:
model = DotProductBias(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.848930</td><td>0.933637</td><td>00:08</td></tr><tr><td>1</td><td>0.572976</td><td>0.916287</td><td>00:08</td></tr><tr><td>2</td><td>0.399092</td><td>0.943160</td><td>00:07</td></tr><tr><td>3</td><td>0.313963</td><td>0.953959</td><td>00:08</td></tr><tr><td>4</td><td>0.289310</td><td>0.955959</td><td>00:07</td></tr></tbody></table></div>

In [22]:
model = DotProductBias(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.1)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.853044</td><td>0.940095</td><td>00:07</td></tr><tr><td>1</td><td>0.653139</td><td>0.887867</td><td>00:07</td></tr><tr><td>2</td><td>0.528025</td><td>0.873233</td><td>00:07</td></tr><tr><td>3</td><td>0.433806</td><td>0.859722</td><td>00:08</td></tr><tr><td>4</td><td>0.433229</td><td>0.855636</td><td>00:08</td></tr></tbody></table></div>

In [23]:
def create_params(size):
  return nn.Parameter(torch.zeros(*size).normal_(0, 0.01))

In [28]:
class DotProductBias(Module):
  def __init__(self, n_users, n_movies, n_factors, y_range = (0.5,5.5)):
    self.user_factors = create_params([n_users, n_factors])
    self.user_bias = create_params([n_users])
    self.movie_factors = create_params([n_movies, n_factors])
    self.movie_bias = create_params([n_movies])
    self.y_range = y_range

  def forward(self, x):
    users = self.user_factors[x[:,0]]
    movies = self.movie_factors[x[:,1]]
    res = (users * movies).sum(dim = 1)
    res += self.user_bias[x[:,0]] + self.movie_bias[x[:,1]]
    return sigmoid_range(res,*self.y_range)

In [29]:
model = DotProductBias(n_users, n_movies, 50)
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.1)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.879097</td><td>0.944574</td><td>00:08</td></tr><tr><td>1</td><td>0.648569</td><td>0.882486</td><td>00:08</td></tr><tr><td>2</td><td>0.523667</td><td>0.868608</td><td>00:07</td></tr><tr><td>3</td><td>0.447138</td><td>0.856993</td><td>00:08</td></tr><tr><td>4</td><td>0.402680</td><td>0.852866</td><td>00:10</td></tr></tbody></table></div>

In [30]:
movie_bias = learn.model.movie_bias.squeeze()

In [31]:
idxs = movie_bias.argsort()[:5]

In [32]:
[dls.classes['title'][i] for i in idxs]

['Children of the Corn: The Gathering (1996)',
 'Mortal Kombat: Annihilation (1997)',
 'Island of Dr. Moreau, The (1996)',
 'Speed 2: Cruise Control (1997)',
 'Vampire in Brooklyn (1995)']

In [33]:
idxs = movie_bias.argsort(descending=True)[:5]
[dls.classes['title'][i] for i in idxs]

["Schindler's List (1993)",
 'Silence of the Lambs, The (1991)',
 'Titanic (1997)',
 'Shawshank Redemption, The (1994)',
 'Star Wars (1977)']

In [34]:
learn = collab_learner(dls, n_factors=50, y_range=(0, 5.5))
learn.fit_one_cycle(5, 5e-3, wd=0.1)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.901855</td><td>0.950038</td><td>00:08</td></tr><tr><td>1</td><td>0.684317</td><td>0.889958</td><td>00:07</td></tr><tr><td>2</td><td>0.517173</td><td>0.872811</td><td>00:08</td></tr><tr><td>3</td><td>0.460999</td><td>0.859981</td><td>00:07</td></tr><tr><td>4</td><td>0.428444</td><td>0.855249</td><td>00:08</td></tr></tbody></table></div>

In [35]:
learn.model

EmbeddingDotBias(
  (u_weight): Embedding(944, 50)
  (i_weight): Embedding(1665, 50)
  (u_bias): Embedding(944, 1)
  (i_bias): Embedding(1665, 1)
)

In [36]:
movie_bias = learn.model.i_bias.weight.squeeze()
idxs = movie_bias.argsort(descending=True)[:5]
[dls.classes['title'][i] for i in idxs]

['Shawshank Redemption, The (1994)',
 'Titanic (1997)',
 'Silence of the Lambs, The (1991)',
 'Close Shave, A (1995)',
 'L.A. Confidential (1997)']

In [39]:
movie_factors = learn.model.i_weight.weight
idx = dls.classes['title'].o2i['Silence of the Lambs, The (1991)']
distances = nn.CosineSimilarity(dim=1)(movie_factors, movie_factors[idx][None])
idx = distances.argsort(descending=True)[1:5]
dls.classes['title'][idx]

['Glory (1989)', 'Shawshank Redemption, The (1994)', 'Hour of the Pig, The (1993)', 'Casablanca (1942)']

In [40]:
embs = get_emb_sz(dls)
embs

[(944, 74), (1665, 102)]

In [41]:
class CollabNN(Module):
  def __init__(self, user_sz, item_sz, y_range = (0.5,5.5), n_act = 100):
    self.user_factors = Embedding(*user_sz)
    self.item_factors = Embedding(*item_sz)
    self.layers = nn.Sequential(
        nn.Linear(user_sz[1] + item_sz[1], n_act),
        nn.ReLU(),
        nn.Linear(n_act, 1)
    )
    self.y_range = y_range

  def forward(self, x):
    embs = self.user_factors(x[:,0]), self.item_factors(x[:,1])
    x = self.layers(torch.cat(embs, dim = 1))
    return sigmoid_range(x, *self.y_range)

In [42]:
model = CollabNN(*embs)

In [43]:
learn = Learner(dls, model, loss_func=MSELossFlat())
learn.fit_one_cycle(5, 5e-3, wd=0.01)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.911467</td><td>0.948550</td><td>00:10</td></tr><tr><td>1</td><td>0.821623</td><td>0.914928</td><td>00:08</td></tr><tr><td>2</td><td>0.805378</td><td>0.888130</td><td>00:08</td></tr><tr><td>3</td><td>0.789052</td><td>0.875574</td><td>00:09</td></tr><tr><td>4</td><td>0.752344</td><td>0.867059</td><td>00:08</td></tr></tbody></table></div>

In [44]:
learn = collab_learner(dls, use_nn=True, y_range=(0, 5.5), layers=[100,50])
learn.fit_one_cycle(5, 5e-3, wd=0.1)

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>0.940117</td><td>0.983705</td><td>00:11</td></tr><tr><td>1</td><td>0.899433</td><td>0.923834</td><td>00:10</td></tr><tr><td>2</td><td>0.819529</td><td>0.896077</td><td>00:10</td></tr><tr><td>3</td><td>0.754200</td><td>0.884265</td><td>00:10</td></tr><tr><td>4</td><td>0.748540</td><td>0.875409</td><td>00:10</td></tr></tbody></table></div>